src/carts/urls.py
from django.urls import path, re_path




from .views import cart_home, cart_update, checkout_home, checkout_done_view


urlpatterns = [
    path('', cart_home, name='home'), 
    path('checkout/success/', checkout_done_view, name='success'),  
    path('checkout', checkout_home, name='checkout'),  
    path('update', cart_update, name='update'),  
    
    
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, re_path, include
from django.views.generic import TemplateView


from accounts.views import LoginView, RegisterView, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from billing.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view
from .views import *




urlpatterns = [
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('', home_page, name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('billing/payment-method/', payment_method_view, name='billing-payment-method'),
    path('billing/payment-method/create/', payment_method_view, name='billing-payment-method-endpoint'),
    path('register/', RegisterView.as_view(), name='register'),
    path('about/', About, name='about'),
    path('contact/', Contact, name='contact'),
    path('api/cart/', cart_detail_api_view, name='api-cart'), 
    path('cart/', include(("carts.urls", 'carts'), namespace='cart')), 
    path('products/', include(("products.urls", 'products'), namespace='products')), 
    path('search/', include(("search.urls", 'search'), namespace='search')), 

    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/carts/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from products.models import Product

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user 
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session ['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated :
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user        = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=00.00, max_digits=10, decimal_places=2)
    total       = models.DecimalField(default=00.00, max_digits=10, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)


    objects = CartManager()


    def __str__(self):
        return str(self.id)



def m2m_changed_cart_receiver(sender,  instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

def pre_save_cart_receiver(sender,  instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = float(instance.subtotal) * float(1.08)
    else:
        instance.total = 0.00
    

pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/carts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect

from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from addresses.models import Address
from billing.models import BillingProfil
from orders.models import Order
from products.models import Product
from .models import Cart



def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
        "id":x.id,
        "url":x.get_absolute_url(),
        "name":x.name, 
        "price":x.price
        } 
        for x in cart_obj.products.all()
        ]


    cart_data = {"products":products,"subtotal":cart_obj.subtotal, "total":cart_obj.total}
    return JsonResponse(cart_data)

def cart_home(request):

    cart_obj, new_obj = Cart.objects.new_or_get(request)

    return render(request, "carts/home.html", {"cart":cart_obj})



def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id  )
        except Product.DoesNotExist:
            print("product is gone!!")
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove (product_obj)
            added = False
        else:
            cart_obj.products.add(product_obj)
            added = True
        request.session['cart_items'] = cart_obj.products.count()
        if request.is_ajax():
            json_data = {
                "added": added,
                "removed": not added,
                "cartItemsCount": cart_obj.products.count()

            }
            return JsonResponse(json_data)
    return redirect("cart:home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0 :
        return redirect("cart:home")
    
    login_form              = LoginForm()
    guest_form              = GuestForm()
    address_form            = AddressForm()
    billing_address_id      = request.session.get("billing_address_id", None)
    shipping_address_id     = request.session.get("shipping_address_id", None)

    billing_profile, billing_profile_created = BillingProfil.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id) 
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()
        
    if request.method == "POST":
        "some check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:success")

            
    context = {
        "object":order_obj,
        "billing_profile":billing_profile,
        "login_form":login_form,
        "guest_form":guest_form,
        "address_form":address_form,
        "address_qs":address_qs,
    }

    return render(request, "carts/checkout.html", context)



def checkout_done_view(request):
    return render(request, "home_page.html", {})

src/carts/templates/carts/checkout-done.html
{% extends 'base.html' %}


{% block content %}

<div class='col-6 mx-auto py-5 text-center'>

    <h1 class='display-1'> Thank you for your order!!! </h1>

</dive>

{% endblock content %}

src/carts/templates/carts/checkout.html
{% extends 'base.html' %}

{% block content %}

{% if not billing_profile %}
    <div class="container">
        <div class="row">
            <div class="col 6">
                <div class="card bg-light mb-3">
                    <div class="card-header bg-success text-white text-center">
                        <i class="fa fa-sign-in" aria-hidden="true"></i> Login </div>
                    <div class="card-body">
                        <div class="col-8">
                            {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}     
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-6">
                <div class="card bg-light mb-3">
                    <div class="card-header bg-success text-white  text-center">
                    <i class="fa fa-question-circle-o" aria-hidden="true"></i> Continue as a guest  </div>
                    <div class="card-body">
                        <div class="col-8">
                            {% url "guest_register" as guest_register_url %}
                            {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url%}
                            <br>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
{% else %}

    {% if not object.shipping_address %}
        <div class='container'>
            <div class='row justify-content-center' >
                <div class='col-8'>
                    <div class='card'>
                        <div class='card-body'>
                            <div class="d-flex justify-content-center">
                                <h3 id="form-title">Shipping Address </h3>
                            </div>
                            <hr/>
                            <div class='col-6'>
                                {% url "checkout_address_create" as checkout_address_create %}
                                {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}'
                            </div>
                            
                            
                        </div>
                        
                    </div>
                </div>
                <div class='col-4'>
                    {% url 'checkout_address_reuse' as checkout_address_reuse %}
                    {% include 'addresses/prev-addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri action_url=checkout_address_reuse address_type='shipping' %}
                </div>
            </div>
        </div>

    {% elif not object.billing_address %}

        <div class='container'>
            <div class='row justify-content-center' >
                <div class='col-8'>
                    <div class='card'>
                        <div class='card-body'>
                            <div class="d-flex justify-content-center">
                                <h3 id="form-title">Billing Address </h3>
                            </div>
                            <hr/>
                            <div class='col-6'>
                                {% url "checkout_address_create" as checkout_address_create %}
                                {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
                            </div>
                            
                            
                        </div>
                        
                    </div>
                </div>
                <div class='col-4'>
                    {% url 'checkout_address_reuse' as checkout_address_reuse %}
                    {% include 'addresses/prev-addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri action_url=checkout_address_reuse address_type='billing' %}
                </div>
            </div>
        </div>
        
        
    {% else %}
        <div class='container'>
            <div class='row justify-content-center' >
                <div class='col-8'>
                    <div class='card'>
                        <div class='card-body'>
                            <div class="d-flex justify-content-center">
                                <h3 id="form-title"> Finalize Checkout </h3>
                            </div>
                            <hr/>
                            <p>Cart Items: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %} </p>
                            <p>Shipping Address: {{ object.shipping_address.get_address }} </p>
                            <p>Billing Address: {{ object.shipping_address.get_address }} </p>
                            <p>Cart total: {{ object.cart.total }} </p>
                            <p>Shipping total: {{ object.shipping_total }} </p>
                            <p>order total: {{ object.total }} </p>
                            <form class='form' method='POST' action="">{% csrf_token %}
                                <button typr='submit' class='btn btn-success'> Checkout </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
                        
    {% endif %}

{% endif %}



{% endblock content %}

src/carts/templates/carts/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Cart</h1>

{% if cart.products.exists  %}

<table class="table cart-table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product Name</th>
      <th scope="col">Product Price</th>
    </tr>
  </thead>
  <tbody class='cart-body'>
    
      {% for product in cart.products.all %}
        <tr class='cart-product'>
          <th scope="row">{{ forloop.counter }}</th>
          <td>
          <a href="{{ product.get_absolute_url }}"> {{ product.title }} </a>
          {% include 'carts/snippets/remove-product.html ' with product_id=product.id  %}
          </td>
          <td>{{ product.price }}</td>
          
        </tr>
      {% endfor %}
    
    <tr>
      <td colspan='2'></td>
      <td><b>subtotal</b> <span class='cart-subtotal'> {{ cart.subtotal }}</span> MAD</td>
    </tr>
    <tr>
      <td colspan='2'></td>
      <td><b>Total</b> <span class='cart-total'> {{ cart.total }}</span> MAD</td>
    </tr>
    <tr>
      <td colspan='2'></td>
      <td><a class='btn btn-lg btn-success' href='{% url 'cart:checkout' %}'>checkout </a></td>
    </tr>
  </tbody>
</table>
<div class='cart-item-remove-form' style='display:none'>
  {% include 'carts/snippets/remove-product.html ' %}
</div>


{% else %}

<p class='lead'> Cart is empty </p>

{% endif %}


{% endblock content %}